import { Router } from 'express';
import toolRoutes from '@features/tool/routes/tool.routes.ts';
import toolRoleRoutes from '@features/tool/routes/toolRole.routes.ts';
import toolIndustryRoutes from '@features/tool/routes/toolIndustry.routes.ts';
import userRoutes from '@features/user/routes/user.routes.ts';
import categoryRoutes from '@features/category/routes/category.routes.ts';
import tagRoutes from '@features/tag/routes/tag.routes.ts';
import toolSubmissionRoutes from '@features/tool/routes/toolSubmission.routes.ts';
import toolTagRoutes from '@features/tool/routes/toolTag.routes.ts';
import toolClaimRoutes from '@features/tool/routes/toolClaim.routes.ts';
import reviewRoutes from '@features/review/routes/review.routes.ts';
import promptRoutes from '@features/prompt/routes/prompt.routes.ts';
import glossaryRoutes from '@features/glossary/routes/glossary.routes.ts';
import newsRoutes from '@features/news/routes/news.routes.ts';
import articleRoutes from '@features/article/routes/article.routes.ts';
import learningRoutes from '@features/learning/routes/learning.routes.ts';
import authRoutes from '@features/user/routes/auth.routes.ts';
import awsRoutes from '@features/aws/routes/aws.routes.ts';
import newsletterRoutes from '@features/newsletter/routes/newsletter.routes.ts';
import bookmarkRoutes from '@features/bookmark/routes/bookmark.routes.ts';
import relatedRoutes from '@features/relatedness/routes/relatedness.routes.ts';
import commentRoutes from '@features/comment/routes/comment.routes.ts';
import importExportRoutes from '@features/import-export/routes/importExport.routes.ts';
import homeRoutes from '@features/home/routes/home.routes.ts';
import activityRoutes from '@features/activity/routes/activity.routes.ts';
import notificationRoutes from '@features/notification/routes/notification.routes.ts';
import siteRoutes from '@features/site/routes/site.routes.ts';

const router = Router();

router.use('/tools', toolRoutes);
router.use('/tool-roles', toolRoleRoutes);
router.use('/tool-industries', toolIndustryRoutes);
router.use('/users', userRoutes);
router.use('/categories', categoryRoutes);
router.use('/tags', tagRoutes);
router.use('/tool-submissions', toolSubmissionRoutes);
router.use('/tool-tags', toolTagRoutes);
router.use('/tool-claims', toolClaimRoutes);
router.use('/reviews', reviewRoutes);
router.use('/prompts', promptRoutes);
router.use('/glossary', glossaryRoutes);
router.use('/news', newsRoutes);
router.use('/articles', articleRoutes);
router.use('/learnings', learningRoutes);
router.use('/auth', authRoutes);
router.use('/aws', awsRoutes);
router.use('/newsletters', newsletterRoutes);
router.use('/bookmarks', bookmarkRoutes);
router.use('/related', relatedRoutes);
router.use('/comments', commentRoutes);
router.use('/import-export', importExportRoutes);
router.use('/home', homeRoutes);
router.use('/activity', activityRoutes);
router.use('/notifications', notificationRoutes);
router.use('/site', siteRoutes);

export default router;
