import type { Metadata } from "next";
import { Inter, Nunito } from "next/font/google";
import "./globals.css";
import QueryProvider from "@/providers/query-provider";
import Shell from "@/components/layout/Shell";
import { AuthProvider } from "@/contexts/AuthContext";
import { Toaster } from "react-hot-toast";
import { ClerkProvider } from "@clerk/nextjs";
import React from "react";
export const dynamic = 'force-dynamic';
const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const nunito = Nunito({
  variable: "--font-nunito",
  subsets: ["latin"],
  weight: ["400", "600", "700", "800"],
});

export const metadata: Metadata = {
  title: "Ai Tools Hub",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({
  children,
  modal,
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <link
          rel="preconnect"
          href="https://fonts.googleapis.com"
          crossOrigin="anonymous"
        />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="anonymous"
        />
      </head>
      <body
        className={`${inter.variable} ${nunito.variable} antialiased`}
        suppressHydrationWarning
      >
        <ClerkProvider
          appearance={{
            elements: {
              formButtonPrimary: "bg-blue-600 hover:bg-blue-700 text-white",
              card: "shadow-lg border border-gray-200",
              headerTitle: "text-2xl font-bold text-gray-900",
              headerSubtitle: "text-gray-600",
              socialButtonsBlockButton:
                "border border-gray-300 hover:bg-gray-50",
              socialButtonsBlockButtonText: "text-gray-700 font-medium",
              dividerLine: "bg-gray-200",
              dividerText: "text-gray-500 bg-white px-2",
            },
            layout: {
              socialButtonsPlacement: "bottom",
              showOptionalFields: false,
            },
            variables: {
              colorPrimary: "#007AFF",
              colorText: "#1F2937",
              colorTextSecondary: "#6B7280",
              colorBackground: "#FFFFFF",
              colorInputBackground: "#F9FAFB",
              colorInputText: "#1F2937",
            },
          }}
        >
          <QueryProvider>
            <AuthProvider>
              <Toaster />
              <Shell>
                {children}
                {modal}
              </Shell>
            </AuthProvider>
          </QueryProvider>
        </ClerkProvider>
      </body>
    </html>
  );
}
